
" use '*' to search to desired section
" Options
" Keymaps
" Insertions

call plug#begin('~/.vim/plugged')

Plug 'junegunn/seoul256.vim'                    " color schemes
Plug 'NLKNguyen/papercolor-theme'
Plug 'sainnhe/everforest'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'                         " fuzzy search
Plug 'tpope/vim-vinegar'                        " file broser
Plug 'vim-scripts/vim-auto-save'                "  auto save
Plug 'tpope/vim-commentary'                     " comment bindings
Plug 'tpope/vim-surround'                       " change brackets, parents, quotes, html tags
Plug 'tpope/vim-repeat'                         " repeat plugin actions
Plug 'tpope/vim-abolish'                        " covert camel case to snake case etc.
Plug 'ludovicchabant/vim-gutentags'             " auto update tags file
Plug 'maralla/completor.vim'                    " better autocomplete, always on
Plug 'maralla/validator.vim'                    " code validation
Plug 'valloric/MatchTagAlways'                  " highlight matching html tags
Plug 'alvan/vim-closetag'                       " automatically close html tags
Plug 'AndrewRadev/splitjoin.vim'                " split single linees into multiple
Plug 'voldikss/vim-floaterm'                    " floating terminal
" Plug 'SirVer/ultisnips'                         " snippets
" Plug 'LunarWatcher/auto-pairs'                " auto pairs
Plug 'kalekundert/vim-coiled-snake'             " python folding

call plug#end()


" Color
" -------------------------------------------

" seoul256 light
"   Range:   252 (darkest) ~ 256 (lightest)
"   Default: 253
let g:seoul256_background = 254
set background=light
colorscheme seoul256-light

" papercolor
" set background=light
" colorscheme PaperColor

" everforest
" set termguicolors
" let &t_8f = '\<Esc>[38;2;%lu;%lu;%lum'
" let &t_8b = '\<Esc>[48;2;%lu;%lu;%lum'
" set background=dark
" let g:everforest_background = 'soft'
" let g:everforest_better_performance = 1
" let g:everforest_disable_italic_comment = 1
" colorscheme everforest

" Options
" -------------------------------------------

set nocompatible
filetype plugin on

" set statusline to gray
autocmd VimEnter * hi StatusLine ctermfg=8 ctermbg=250 cterm=none

" Floating Terminal
let g:floaterm_height=0.8
let g:floaterm_width=0.8
let g:floaterm_borderchars="        "

" Completor
autocmd Filetype markdown let g:completor_auto_trigger = 0
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"

" Validator
let g:validator_python_checkers = ['flake8']
let g:validator_css_checkers = ['csslint']

set ignorecase                          " ignore case
set smartcase                           " except when an upper case character is used
set incsearch                           " start searching as it is typed
set hlsearch                            " highlight search patterns
set mouse=a                             " enable mouse usage
set noswapfile                          " no swap files
set splitright                          " open splits on the right
set splitbelow                          " open splits on bottom
set foldmethod=indent                   " fold behavior
set foldlevel=99
let g:auto_save = 1                     " autosave
let g:auto_save_in_insert_mode = 0
set expandtab                           " inserts spaces when tab key is pressed
set tabstop=4                           " sets for spaces for tabs
set softtabstop=4                       " number of spaces removed by backspace key
set shiftwidth=4                        " sets number of spaces to insert/remove using indentation commands
set autoindent
set shiftround                          " use multiple of shiftwidth when indenting with '<' and '>'
set backspace=indent,eol,start          " backspace
set ttimeoutlen=50                      " elminiate delay in escaping out of fzf
set undofile                            " persistent undo history
set undodir=~/.vim/undodir
set wildignore+=tags,.git/**
set wildignore+=**/migrations/**
set wildignore+=**/__pycache__/**
set wildignore+=static/bootstrap-3.3.7/**,static/images/**
set wildignore+=static/admin/**
set viminfofile=~/.vim/viminfo          " move viminfo to vim folder
set signcolumn=number                   " prevent signs from opening another gutter
set number                              " always show line numbers
set relativenumber
set nowrap                              " wrap lines
set linebreak                           " break at whitespace not words
set display=lastline                    " show partial lines at the bottom of the screen

" enable resizing splits in tmux
if has("mouse_sgr")
    set ttymouse=sgr
else
    set ttymouse=xterm2
end

" auto remove trailing whitespace
autocmd BufWritePre * :%s/\s\+$//e

" tabs for css and html
autocmd BufRead,BufNewFile *.html,*.css setlocal tabstop=2 shiftwidth=2 softtabstop=2

" html mode
autocmd BufRead,BufNewFile *.html setlocal filetype=htmldjango foldmethod=indent


" Keymaps
" -------------------------------------------

" leader
let mapleader = " "

" escaping
inoremap jj <esc>
inoremap jk <esc>

" kill buffer
nnoremap <S-k> :bd<cr>

" exit vim
nnoremap <C-d> :q!<cr>

" pg up/down
nnoremap <C-m> <C-d>

" window navigation
nnoremap <tab> <C-w>w
nnoremap <S-tab> <C-w>W
nnoremap <leader>v :vsp<cr>

" clear highlighted search text until next explicit search or n/N
" <silent> - so as to not print :noh on last line when invoked
nnoremap <silent> <leader><space> :noh<cr>

" fzf searches
nnoremap <leader>f :Files<cr>
nnoremap <nowait><leader>b :Buffers<cr>
nnoremap <leader>r :Rg<cr>

" quickfix window
nnoremap <leader>c :copen 10<cr>
nnoremap ]q :cnext<cr>zz

" search for word under cursor, including first word
nnoremap * *N

" search for visually selected text
vnoremap * y/\V<C-R>=escape(@",'/\')<CR><CR>N

" shortcuts to edit configuation files
nnoremap <leader>ev :e $MYVIMRC<cr>
nnoremap <leader>so :so %<cr>
nnoremap <leader>eb :e ~/.bashrc<cr>
nnoremap <leader>et :e ~/.tmux.conf<cr>
nnoremap <leader>ed :e ~/.dotfiles<cr>

" shortcut to view log files
nnoremap <leader>l :e /var/log/gunicorn<cr>

" save as root
command W :execute ':silent w !sudo tee % > /dev/null' | :edit!

" insert a breakpoint
nnoremap <leader>p obreakpoint()<Esc>

" Float term toggle
nnoremap <leader>t :FloatermToggle<cr>


" Insertion
" -------------------------------------------

" auto close pairs when on separate lines
inoremap {<cr> {<cr>}<esc>O
inoremap [<cr> [<cr>]<esc>O
inoremap (<cr> (<cr>)<esc>O

" insert text
func Eatchar(pat)
    let c = nr2char(getchar(0))
    return (c =~ a:pat) ? '' : c
endfunc

" print
iab pr print()<left><c-r>=Eatchar('\s')<cr>

" pprint
iab ppr from pprint import pprint<cr>pprint()<left><c-r>=Eatchar('\s')<cr>

" javascript console log
iab cl console.log();<left><left><c-r>=Eatchar('\s')<cr>
"
" dump django objects to browser
iab dd import config.helpers as helpers<cr>return helpers.dump()<left><c-r>=Eatchar('\s')<cr>

" python dosctring
iab pycom """<cr><cr>Args:<cr>    id (int):<cr><bs><cr>Returns:<cr><cr>Notes:<cr><cr>"""<up><up><up><up><up><up><up><up><up><c-r>=Eatchar('\s')<cr>

" css section
iab csscom /*------------------------------------------------<cr><cr>------------------------------------------------*/<up>

function! JumpToCSS()
  let id_pos = searchpos("id", "nb", line('.'))[1]
  let class_pos = searchpos("class", "nb", line('.'))[1]

  if class_pos > 0 || id_pos > 0
    if class_pos < id_pos
      execute ":vim '#".expand('<cword>')."' **/*.css"
    elseif class_pos > id_pos
      execute ":vim '.".expand('<cword>')."' **/*.css"
    endif
  endif
endfunction

nnoremap <F9> :call JumpToCSS()<CR>

autocmd InsertEnter * set cursorline
autocmd InsertLeave * set nocursorline

